name: NoElytraBoost
version: 1.0.0
main: com.noelytraboost.NoElytraBoostPlugin
api-version: "1.21"
author: rieckt
description: Prevents firework rocket boost while gliding with elytra by anchoring player velocity.
